using Contracts;
using FastEndpoints;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Server;

var bld = WebApplication.CreateBuilder();
bld.WebHost.ConfigureKestrel(
    k =>
    {
        // for GRPC
        k.ListenLocalhost(
            6000,
            o =>
            {
                o.Protocols = HttpProtocols.Http2;

                //self-signed cert generated by: https://selfsigned.org
                //WARNING: do not store and distribute ssl certificates with your app!!!
                //         this pfx file is stored in the git repo for demonstration only.
                o.UseHttps("ssl-cert/localhost.pfx", "password");
            });

        // for REST
        k.ListenLocalhost(
            5001,
            o => o.Protocols = HttpProtocols.Http1AndHttp2);
    });
bld.AddHandlerServer();

var app = bld.Build();
app.MapHandlers(
    h =>
    {
        h.Register<SayHelloCommand, SayHelloHandler>();
    });

app.Run();